# Generated by Django 3.0.4 on 2020-03-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisanistan', '0002_croplists'),
    ]

    operations = [
        migrations.AddField(
            model_name='croplists',
            name='media',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
