# Generated by Django 3.0.4 on 2020-03-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kisanistan', '0003_croplists_media'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='croplists',
            new_name='croplist',
        ),
    ]
