# Generated by Django 3.0.4 on 2020-03-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kisanistan', '0005_crop_detail_disease_detail_fertilizer_detail_pesticide_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='disease_detail',
            new_name='cropdetail',
        ),
        migrations.RenameModel(
            old_name='fertilizer_detail',
            new_name='diseasedetail',
        ),
        migrations.RenameModel(
            old_name='crop_detail',
            new_name='fertilizerdetail',
        ),
        migrations.RenameModel(
            old_name='pesticide_detail',
            new_name='pesticidedetail',
        ),
    ]
