# Generated by Django 3.0.4 on 2020-03-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisanistan', '0006_auto_20200322_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropdetail',
            name='detail',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='diseasedetail',
            name='detail',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='fertilizerdetail',
            name='detail',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='pesticidedetail',
            name='detail',
            field=models.CharField(max_length=2000),
        ),
    ]
