# Generated by Django 3.0.4 on 2020-03-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisanistan', '0007_auto_20200322_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('emailaddress', models.CharField(max_length=60)),
                ('season', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=60)),
            ],
        ),
    ]
